on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:  
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env: 
          MYSQL_ROOT_PASSWORD: "password"
          MYSQL_DATABASE: "mn_playground"
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: setup java
        uses: actions/setup-java@v4
        with: 
          distribution: 'temurin'
          java-version: '21'
          
      - name: setup gradle
        uses: gradle/actions/setup-gradle@v4
                      
      - name: Build with gradle
        run: gradle build
        env:
          DATASOURCES_DEFAULT_URL: "jdbc:mysql://localhost:3306/mn_playground"
            
